name: Rust CI

on:
  push:
    branches: [ main ] # Assuming 'main' is the main branch
  pull_request:
    branches: [ main ] # Assuming 'main' is the main branch

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build, Format, Lint, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Check formatting (rustfmt)
        run: cargo fmt -- --check

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test
